# Generated by Django 5.0.6 on 2024-05-19 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pays', to='MyApp.continent')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='images/')),
                ('maxJoueurs', models.IntegerField()),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes', to='MyApp.continent')),
                ('pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes', to='MyApp.pays')),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('genre', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/')),
                ('pace', models.PositiveIntegerField(default=50)),
                ('defense', models.PositiveIntegerField(default=50)),
                ('dribbling', models.PositiveIntegerField(default=50)),
                ('passing', models.PositiveIntegerField(default=50)),
                ('physical', models.PositiveIntegerField(default=50)),
                ('shooting', models.PositiveIntegerField(default=50)),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joueurs', to='MyApp.equipe')),
                ('pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joueurs', to='MyApp.pays')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joueurs', to='MyApp.role')),
            ],
        ),
    ]
