# Generated by Django 5.0.6 on 2024-05-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pays',
            name='ville',
        ),
    ]
