# Generated by Django 5.0.6 on 2024-05-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
