# Generated by Django 5.0.6 on 2024-05-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_remove_pays_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
    ]
