# Generated by Django 5.0.6 on 2024-05-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_joueur_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='logo',
            field=models.ImageField(upload_to='images/club'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='photo',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/players'),
        ),
    ]
