# Generated by Django 5.0.6 on 2024-05-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_joueur_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='ville',
        ),
    ]
