# Generated by Django 5.0.6 on 2024-05-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_equipe_logo_alter_joueur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='logo',
            field=models.ImageField(blank=True, default='images/defaultClub.jpg', null=True, upload_to='images/club'),
        ),
    ]
