# Generated by Django 5.0.6 on 2024-05-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_remove_equipe_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='photo',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='continent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pays', to='MyApp.continent'),
        ),
    ]
