# Generated by Django 5.0.6 on 2024-05-17 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_alter_joueur_photo_alter_pays_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='continent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to='MyApp.continent'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='pays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pays', to='MyApp.pays'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to='MyApp.equipe'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='MyApp.role'),
        ),
    ]
