# Generated by Django 5.0.6 on 2024-05-17 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_alter_equipe_continent_alter_equipe_pays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='continent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes', to='MyApp.continent'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='pays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes', to='MyApp.pays'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joueurs', to='MyApp.equipe'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='pays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joueurs', to='MyApp.pays'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joueurs', to='MyApp.role'),
        ),
    ]
